name: iOS starter workflow

on:
  push:
    branches: [ initial-github-actions ]
    
jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    
    strategy:
      matrix: 
        destination: ["'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=latest'"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build for testing
        env:
          scheme: ${{ 'default' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          xcodebuild -scheme "$scheme" -destination ${{ matrix.destination }}
      - name: Test
        env:
          scheme: ${{ 'default' }}
        run: | 
          # if [ $scheme = default ]; then scheme=$(cat default); fi
          # xcodebuild test-without-building -scheme "$scheme" -destination ${{ matrix.destination }}
