name: iOS starter workflow

on:
  push:
    branches: [ initial-github-actions ]
    
jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    
    strategy:
      matrix: 
        destination: ["'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.2'"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: xcodebuild build-for-testing -scheme "$scheme" -destination ${{ matrix.destination }}
      - name: Test
        env:
          scheme: ${{ 'default' }}
        run: xcodebuild test-without-building -scheme "$scheme" -destination ${{ matrix.destination }}
